project:
  type: website

website:
  title: "Data Science and Statistics in R for Fellowship"
  repo-url: https://github.com/Caius-Gibeily/r-training-fellowship
  repo-actions: [edit, issue]
  repo-subdir: "docs"
  page-navigation: true
  sidebar:
    contents:

      - href: index.qmd
      #- section: R for Data Science 2025
      #  contents:
      #    - r4dss25/intro.qmd
      #    - r4dss25/s1_data-visualization_transform.qmd
      #    - r4dss25/s2_data-tidying_import.qmd
      #    - r4dss25/s3_layers_exploratory.qmd
      #    - r4dss25/s4_vectors-numbers-strings.qmd
      #    - r4dss25/s5_factors-nas.qmd
      #- section: Supplementary exercises for R4DS
      #  contents: 
      #    - getting_started/rimporting_data.qmd
      #    - getting_started/rdata_types.qmd
      #    - getting_started/rdata_structures2.qmd
      #    - getting_started/rindexing.qmd
      - section: Introduction to Statistics in R
        contents:
          - isr/intro.qmd
          - isr/variance.qmd
          - isr/cov.qmd
          - isr/se.qmd
          - isr/perm_hyp.qmd
          - isr/power2.qmd
          - isr/ANOVA.qmd
          - isr/Post_hoc2.qmd
          - isr/stats_journal_club.qmd
          - isr/RM-ANOVA.qmd
          - isr/chisq.qmd
          - isr/Linear_regression.qmd
          - isr/p_hacking.qmd
          - isr/logistic_regression.qmd
          - isr/gams.qmd
          
      # - section: Exercises and Grading
      #   contents:
      #     - exercises/exercises.qmd
      #     - exercises/grading.qmd
      #     - exercises/gradethis.qmd
      #     - exercises/environments.qmd
      # - section: Interactive Documents and Tutorials
      #   contents:
      #     - interactive/reactivity.qmd
      #     - interactive/data.qmd
      #     - interactive/dynamic.qmd
      #     - interactive/hybrid.qmd
      #     - interactive/dashboards.qmd
      # - section: Other Features
      #   contents:
      #     - other/tables.qmd
      #     - other/resources.qmd
      #     - other/htmlwidgets.qmd
      #     - other/py_output.qmd
      #     - other/slides.qmd
      # - text: "---"
      # - section: Reference
      #   contents:
      #     - reference/document-yaml.qmd
      #     - reference/cell-options.qmd

theme:
  light: cosmo
  dark: darkly
